- name: Install NGINX on EC2
  hosts: all
  become: yes
  
  vars:
    server_name: "{{ ansible_default_ipv4.address | default('localhost') }}"
  
  tasks:
    - name: Install NGINX
      shell: amazon-linux-extras install nginx1 -y

    - name: Start and enable NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create SSL directory
      file:
        path: /etc/ssl/certs
        state: directory
        mode: '0755'

    - name: Generate simple self-signed SSL certificate
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/certs/nginx-selfsigned.key \
        -out /etc/ssl/certs/nginx-selfsigned.crt \
        -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"
      args:
        creates: /etc/ssl/certs/nginx-selfsigned.crt
    
    - name: Create NGINX HTTPS configuration with redirect
      copy:
        content: |
          # Redirect HTTP to HTTPS
          server {
              listen 80;
              server_name _;
              return 301 https://$server_name$request_uri;
          }

          # HTTPS server
          server {
              listen 443 ssl;
              server_name _;

              # SSL configuration
              ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
              ssl_certificate_key /etc/ssl/certs/nginx-selfsigned.key;
              
              # Minimal security settings
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              
              # Basic security headers
              add_header Strict-Transport-Security "max-age=31536000";
              add_header X-Frame-Options DENY;
              add_header X-Content-Type-Options nosniff;

              root /usr/share/nginx/html;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/conf.d/default.conf
        backup: yes
      notify: restart nginx

    - name: Create custom welcome page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>NGINX HTTPS AMI</title>
          </head>
          <body>
              <h1>NGINX HTTPS AMI</h1>
              
              <h2>AMI Information</h2>
              <p>Base Image: Amazon Linux 2 (amzn2-ami-hvm-*-x86_64-gp2)</p>
              <p>AMI Name: nginx-https-{{ build_timestamp | regex_replace('[^0-9]', '') }}</p>
              <p>Build Time: {{ build_timestamp }}</p>

              <h2>Features</h2>
              <p>- Pre-configured NGINX web server</p>
              <p>- Self-signed SSL certificate</p>
              <p>- Automatic HTTP to HTTPS redirect</p>
              <p>- Built with Packer + Ansible automation</p>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart NGINX to apply changes
      systemd:
        name: nginx
        state: restarted

    - name: Display build success message
      debug:
        msg:
          - "NGINX HTTPS AMI build completed successfully."

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted