- hosts: all
  tasks:
    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install packages
      win_shell: choco install nginx openssl nssm -y

    - name: Setup NGINX with HTTPS
      win_shell: |
        $nginx = (Get-Command nginx).Source | Split-Path -Parent
        New-Item "$nginx\conf\ssl" -ItemType Directory -Force
        
        # Generate SSL certificate
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$nginx\conf\ssl\nginx.key" -out "$nginx\conf\ssl\nginx.crt" -subj "/CN=localhost"
        
        # Configure NGINX
        @"
        events { worker_connections 1024; }
        http {
          include mime.types;
          # Redirect HTTP to HTTPS
          server {
              listen 80;
              server_name _;
              return 301 https://`$server_name`$request_uri;
          }

          # HTTPS server
          server {
              listen 443 ssl;
              server_name _;

              # SSL configuration
              ssl_certificate conf/ssl/nginx.crt;
              ssl_certificate_key conf/ssl/nginx.key;
              
              # Minimal security settings
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              
              # Basic security headers
              add_header Strict-Transport-Security "max-age=31536000";
              add_header X-Frame-Options DENY;
              add_header X-Content-Type-Options nosniff;

              root html;
              index index.html;

              location / {
                  try_files `$uri `$uri/ =404;
              }
          }
        }
        "@ | Out-File "$nginx\conf\nginx.conf" -Encoding UTF8
        
        # Create welcome page
        @"
        <!DOCTYPE html>
        <html>
        <head>
            <title>NGINX HTTPS AMI</title>
        </head>
        <body>
            <h1>NGINX HTTPS AMI</h1>
            
            <h2>AMI Information</h2>
            <p>Base Image: Windows_Server-2022-English-Full-Base-*</p>
            
            <h2>Features</h2>
            <p>- Pre-configured Windows NGINX web server</p>
            <p>- Self-signed SSL certificate</p>
            <p>- Automatic HTTP to HTTPS redirect</p>
            <p>- Built with Packer + Ansible automation</p>
        </body>
        </html>
        "@ | Out-File "$nginx\html\index.html" -Encoding UTF8
        
        # Setup Windows service
        nssm install nginx nginx.exe
        nssm set nginx Start SERVICE_AUTO_START
        
        # Configure firewall
        netsh advfirewall firewall add rule name="HTTP" dir=in action=allow protocol=TCP localport=80
        netsh advfirewall firewall add rule name="HTTPS" dir=in action=allow protocol=TCP localport=443
        
        # Start service
        Start-Service nginx